In [2]:
pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 7.3 MB/s eta 0:00:02
   ----- ---------------------------------- 1.8/12.8 MB 9.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.8 MB 9.2 MB/s eta 0:00:01
   ---------------------- ----------------- 7.3/12.8 MB 9.7 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.8 MB 10.1 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.8 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 10.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


use of numpy

Faster than lists

Multidimensional arrays

Broadcasting (apply operations across shapes)

Vectorization (no loops)

 Unlike lists, arrays can only store data of a similar type.

In [19]:
import numpy as np
from time import process_time()

In [30]:
li=[i for i in range (1000000)]
start_time = process_time()
li = [i+5 for i in li]
end_time = process_time()
print(f"{end_time - start_time:.6f}")


0.046875


In [29]:
import numpy as np
from time import process_time

# Create a numpy array with 1 million elements
np_arr = np.array([i for i in range(1000000)])

# Measure the time it takes to add 5 to each element
start_time = process_time()
np_arr += 5  # Vectorized operation to add 5 to each element
end_time = process_time()

# Print the execution time
print(f"Execution time: {end_time - start_time:.6f} seconds")

Execution time: 0.000000 seconds


In [31]:
#numpy arrays


In [32]:
li = [1,2,34,5]
print(type(li))


<class 'list'>


In [33]:
np_arr = np.array([1,2,3,4,5])
print(type(np_arr))

<class 'numpy.ndarray'>


In [36]:
#creating a 1-D array
np_arr = np.array([1,2,3,4,5])
np_arr.shape

(5,)

In [40]:
#2-D array
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape 

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [41]:
b= np.array([(1,2,3,4),(5,6,7,8)],dtype=float)#float type values
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [48]:
#initial placeholders in array

#create numpy of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
#create numpy of value of 5 or any value replace 5 with desired value in last parameter
x=np.full((4,5),5)
print(x)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [47]:
#identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
#create a numpy array with random values
a = np.random.random((3,4))
print(a)

[[0.29589334 0.3877435  0.65491795 0.52223066]
 [0.87635372 0.15415985 0.71047149 0.48356856]
 [0.58330457 0.47126641 0.56567143 0.55184269]]


In [50]:
#create a numpy array with random integers
a = np.random.randint(10,1000,(3,4))
print(a)

[[838 605  47 766]
 [803 151 633  88]
 [715 657 999 433]]


In [53]:
#evenly spaced arrays

a=np.linspace(10,30,5)
print(a)

[10. 15. 20. 25. 30.]


In [55]:
#evenly spaced arrays-->specifying the step

a=np.arange(10,30,4)
print(a)

[10 14 18 22 26]


In [2]:
import numpy as np

# create an empty array of length 4
array1 = np.empty(4)

print(array1)

[0. 0. 0. 0.]


In [3]:
import numpy as np

# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8], 
                [9, 10, 11, 12]],
                     
                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [4]:
import numpy as np

# create 2D array with 2 rows and 3 columns filled with zeros
array1 = np.zeros((2, 3))

print("2-D Array: ")
print(array1)

# create 3D array with dimensions 2x3x4 filled with zeros
array2 = np.zeros((2, 3, 4))

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0. 0. 0.]
 [0. 0. 0.]]

3-D Array: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
import numpy as np

# Create a 2-D array with elements initialized to 5 
numpy_array = np.full((2, 2), 5)

print("Array:", numpy_array)

Array: [[5 5]
 [5 5]]


In [6]:
import numpy as np

# create a 2D array of 2 rows and 2 columns of random numbers
array1 = np.random.rand(2, 2)

print("2-D Array: ")
print(array1)

# create a 3D array of shape (2, 2, 2) of random numbers
array2 = np.random.rand(2, 2, 2)

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0.8886848  0.01663219]
 [0.43861442 0.77808137]]

3-D Array: 
[[[0.00766101 0.63917381]
  [0.91632296 0.00602717]]

 [[0.09968131 0.60374304]
  [0.64570673 0.16400726]]]


In [7]:
import numpy as np

# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)  # prints int64

# check the data type of float_array
print(float_array.dtype)  # prints float64

# check the data type of complex_array
print(complex_array.dtype)  # prints complex128

int64
float64
complex128


In [8]:
import numpy as np

# create an array of 32-bit integers
array1 = np.array([1, 3, 7], dtype='int32')

print(array1, array1.dtype)

[1 3 7] int32


In [9]:
import numpy as np

# create an array of integers
int_array = np.array([1, 3, 5, 7])

# convert data type of int_array to float
float_array = int_array.astype('float')

# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64
